name: Version Package One

on:
  pull_request:
    types: [labeled]
    branches:
      - "main"
      - "release*"
      - "hotfix*"

jobs:
  version-package-one:
    if: ${{ github.event.label.name == 'version-package-one' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm version-package-one"
