name: Version Package One

on:
  pull_request:
    types: [opened, edited, labeled, synchronize]
    branches:
      - "main"
      - "release*"
      - "hotfix*"
      - "version*"

jobs:
  version-package-one:
    if: ${{ github.event.label.name == 'version-package-one' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - run: node_modules/.bin/changeset version --ignore package-two
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Versioning package one and updating changelog
      - run: echo packages/package-one/CHANGELOG.md | xargs node generate-release-notes | read version
      - run: versionStr="v$version"
      - run: gh release create $versionStr -F .changeset/release-notes.md -t "Package One $versionStr"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
