name: Version Package One

on:
  pull_request:
    types: [labeled]
    branches:
      - "main"
      - "release*"
      - "hotfix*"
      - "version*"

jobs:
  version-package-one:
    if: ${{ github.event.label.name == 'version-package-one' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: node_modules/.bin/changeset version --ignore pacakge-two
      - name: commit changes
        shell: bash
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git status
          git add .
          git commit --allow-empty -m "Versioning package one and updating changelog"
