name: Version Package Two

on:
  pull_request:
    types: [labeled]
    branches:
      - "main"
      - "release*"
      - "hotfix*"

jobs:
  version-package-two:
    if: ${{ github.event.label.name == 'version-package-two' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm version-package-two
      - name: commit changes
        shell: bash
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git status
          git add .
          git commit --allow-empty -m "Versioning package two and updating changelog"
